# services (means containers, any apps or databases)
services:
  db-tests-app: # (app/service name) you can give it any name
    # removed container name to be able to scale, for load balancing
    # DockerHub repo, to push image to it
    image: ezzat22/tresmerge-docker
    build: .
    # No PORT Forwarding, as you're already using Nginx => PORT 80
    depends_on:
      # - redis
      - postgres 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # =================== redis =================== #
  redis:
    image: redis

  # =================== Nginx =================== #
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db-tests-app

  # =================== Postgres =================== #
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example


volumes:
  postgres-db: